Add support for spec.schedulingGates in calcDiffSpec
loft-sh/vcluster pull request #1010
Opened 2023-04-17 03:33 UTC by sigmabaryon

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #845

**Please provide a short message that should be published in the vcluster release notes**
Added ability to sync down the `spec.schedulingGates` property in the `calcSpecDiff` function for the pod translator package.

**What else do we need to know?** 
Used `rancher/k3s:v1.26.3-k3s1` image with `--kube-apiserver-arg=feature-gates=PodSchedulingReadiness=true` for the server args in the k3s chart for testing.

2023-04-17 07:59 UTC, FabianKramm requested changes
@sigmabaryon thanks a lot for the PR! LGTM, just 2 small updates

2023-04-17 07:59 UTC, FabianKramm commented on pkg/controllers/resources/pods/translate/translator.go
> +		updatedPodSpec = pObj.Spec.DeepCopy()
Can you add:
```
if updatedPodSpec == nil {
      updatedPodSpec = pObj.Spec.DeepCopy()
}
```

2023-04-17 07:59 UTC, FabianKramm commented on pkg/controllers/resources/pods/translate/translator.go
> +func isPodSpecSchedulingGatesDiff(pGates, vGates []corev1.PodSchedulingGate) ([]corev1.PodSchedulingGate, bool) {
Please just return bool here and then assign via `updatedPodSpec.SchedulingGates = vObj.Spec.SchedulingGates`

2023-04-18 04:45 UTC, sigmabaryon commented
@FabianKramm Thanks for the quick review! I've pushed the review changes. Please take a look.

2023-04-22 06:53 UTC, FabianKramm approved these changes
@sigmabaryon thanks for the update, LGTM now!

2023-04-25 13:44 UTC, merged