Fixed how certain ingress annotations that points to a secret are synced when a namespace is also defined
loft-sh/vcluster pull request #1019
Opened 2023-05-02 14:22 UTC by adiffpirate

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
Fixes how `translateIngressAnnotations` handles namespaces.
- Motivation: The [nginx.ingress.kubernetes.io/auth-tls-secret](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication) annotation requires the format `namespace/secret` to work
- Previous behaviour: Annotations with value `namespace/secret` were translated to `physicalSecret`
- Current behaviour: Annotations with value `namespace/secret` are translated to `physicalNamespace/physicalSecret`

**Please provide a short message that should be published in the vcluster release notes**
Fixed how certain ingress annotations that points to a secret are synced when a namespace is also defined

2023-05-03 06:25 UTC, rohantmp commented
Thanks for the PR :) I'll take a look

2023-05-17 05:27 UTC, rohantmp commented
The proposed desired behavior looks good! 
Ran the unit tests locally, look like they're failing around the other annotations handled by the same function. Could you fix that?

2023-05-17 05:28 UTC, rohantmp requested changes
Can you:
- squash: put the unit tests in the same commit
- fix the failing unit tests

Thanks :)

2023-05-17 14:04 UTC, adiffpirate commented
Done. Appreciate the quick review.

2023-05-18 02:55 UTC, rohantmp approved these changes
LGTM! Thanks a lot :)

2023-05-18 09:16 UTC, matskiv approved these changes
Thank you for your contribution! :raised_hands:

2023-05-18 09:17 UTC, merged