Updated dependencies to latest version
loft-sh/vcluster pull request #1061
Opened 2023-05-31 14:09 UTC by ThomasK33

**What issue type does this pull request address?** (keep at least one, remove the others) 

/kind enhancement

**What does this pull request do? Which issues does it resolve?**

**Please provide a short message that should be published in the vcluster release notes**
Updated dependencies

**What else do we need to know?** 

Signed-off-by: Thomas Kosiewski <thomas.kosiewski@loft.sh>

2023-05-31 14:14 UTC, ThomasK33 commented
Fixes ENG-1498

2023-06-05 18:08 UTC, matskiv reviewed
This looks good overall. Just a few things to discuss, see comments :)

2023-06-05 18:10 UTC, ThomasK33 commented on pkg/controllers/resources/configmaps/syncer.go
> +	err := ctx.VirtualClient.List(s.ctx, podList, client.MatchingFields{constants.IndexByConfigMap: configMap.Namespace + "/" + configMap.Name})
I agree, had this change locally already. Will push it tomorrow. ^^

2023-06-05 18:12 UTC, ThomasK33 commented on cmd/vclusterctl/cmd/connect.go
> +	Ctx context.Context
Yes, but... 😂

For tests and some other cases, one has to be able to inject the context, as otherwise, the application keeps crashing.

2023-06-05 18:37 UTC, matskiv commented on cmd/vclusterctl/cmd/connect.go
> +	Ctx context.Context
Good point, I forgot about e2e tests.
btw, I noticed that two other occurrences of `ConnectCmd{}` don't have the Ctx set:
https://github.com/loft-sh/vcluster/blob/a53ae9273bc1673ac1206dc18c65fa4e1cc9f615/cmd/vclusterctl/cmd/create.go#L217
https://github.com/loft-sh/vcluster/blob/a53ae9273bc1673ac1206dc18c65fa4e1cc9f615/cmd/vclusterctl/cmd/create.go#L241
should it be set?

2023-06-05 18:38 UTC, matskiv commented on pkg/controllers/resources/configmaps/syncer.go
> +	err := ctx.VirtualClient.List(s.ctx, podList, client.MatchingFields{constants.IndexByConfigMap: configMap.Namespace + "/" + configMap.Name})
Cool, thanks! :+1: 
But it is a bit trickier with the "IsManaged" functions, I guess we will have to add Context as a parameter :shrug:

2023-06-06 08:33 UTC, FabianKramm requested changes

2023-06-06 11:46 UTC, ThomasK33 commented on cmd/vclusterctl/cmd/connect.go
> +	Ctx context.Context
Good point, now they are gone entirely

2023-06-06 11:47 UTC, ThomasK33 commented on cmd/vclusterctl/cmd/connect.go
> +	Ctx context.Context
![gone christmas GIF](https://media2.giphy.com/media/XqpnXaeZPnupy/200.gif)

2023-06-06 14:21 UTC, matskiv commented on cmd/vclusterctl/cmd/connect.go
> +	Ctx context.Context
Nice. Thank you

2023-06-06 14:29 UTC, matskiv commented on pkg/server/filters/service.go
> +	ctx := req.Context()
uhm, I hate to be nit picking, but the `ctx := context.Background()` is now in a different place and we lost a valuable comment

2023-06-06 15:12 UTC, ThomasK33 commented on pkg/server/filters/service.go
> +	ctx := req.Context()
![looking forward art gallery GIF by Feliks Tomasz Konczakowski](https://media0.giphy.com/media/3oFzm4yTR1Wqn5XkaI/200.gif)

2023-06-07 08:19 UTC, FabianKramm approved these changes

2023-06-07 08:20 UTC, matskiv approved these changes

2023-06-07 08:20 UTC, merged