fix node labels syncing
loft-sh/vcluster pull request #1259
Opened 2023-09-29 16:22 UTC by ishankhare07

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix
/kind enhancement
/kind test

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1001 ENG-1289

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster node were syncing as `fake-$NAME`. Use `$NAME.nodes.vcluster.com` instead

**What else do we need to know?**

2023-10-02 08:00 UTC, FabianKramm requested changes

2023-10-03 05:30 UTC, ishankhare07 commented on pkg/controllers/resources/nodes/translate.go
> +		labels["kubernetes.io/hostname"] = GetNodeHost(vNode.Name)
Hi @FabianKramm actually the original issue also mentioned
> This should also be done for the "real nodes sync".

And yea I think I added the above line at the wrong place, I will move it out of the if-else block – we should not be ignoring the `enableScheduler` path, thanks for pointing out

2023-10-05 08:53 UTC, FabianKramm requested changes

2023-10-05 08:53 UTC, FabianKramm commented on pkg/controllers/resources/nodes/translate.go
> +		labels, annotations = translate.ApplyMetadata(pNode.Annotations, vNode.Annotations, pNode.Labels, vNode.Labels)
Why is that needed here?

2023-10-06 12:56 UTC, FabianKramm requested changes

2023-10-06 12:56 UTC, FabianKramm commented on pkg/controllers/resources/nodes/translate.go
> +	labels["kubernetes.io/hostname"] = GetNodeHost(vNode.Name)
I think we should only do this if `s.useFakeKubelets` is true as otherwise we won't rewritte the hostname at all

2023-10-06 14:02 UTC, FabianKramm approved these changes

2023-10-06 14:02 UTC, merged