build: add devspace, helm, and kubectl to the vcluster-cli image
loft-sh/vcluster pull request #1284
Opened 2023-10-06 18:51 UTC by lizardruss

**What issue type does this pull request address?**
/kind enhancement

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves ENG-2163

**Please provide a short message that should be published in the vcluster release notes**
Added tools required for GitLab usage example

2023-10-06 19:03 UTC, ThomasK33 requested changes
LGTM, please align the helm version with the one from the other Dockerfile

2023-10-06 19:03 UTC, ThomasK33 commented on Dockerfile.cli.release
> +ARG HELM_VERSION="v3.11.0"
Could you please align this with the helm version in the vCluster Dockerfile?

iirc that one is using a newer version of helm

2023-10-09 08:26 UTC, FabianKramm approved these changes

2023-10-09 09:35 UTC, ThomasK33 approved these changes

2023-10-09 09:35 UTC, merged