fix: ephermeral containers not working on EKS clusters
loft-sh/vcluster pull request #1287
Opened 2023-10-08 06:07 UTC by kirinnee

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1286

**Please provide a short message that should be published in the vcluster release notes**
Migrate version check for Kubernetes from `.Capabilities.KubeVersion.Minor` to `semverCompare`

**What else do we need to know?** 
Refer to issue

2023-10-09 09:26 UTC, ThomasK33 requested changes
`Capabilities.KubeVersion.GitVersion` is [deprecated](https://github.com/helm/helm/blob/c288f0b7bed1f6174afdcdaf8779c5d37b07d7a5/pkg/chartutil/capabilities.go#L82).

Please either rewrite this to use the `.Capabilities.KubeVersion.Version` field or utilize `Capabilities.APIVersions.Has` to check for the availability of ephemeral containers.

2023-10-10 01:05 UTC, kirinnee commented
Updated to `Version` as requested

2023-10-10 12:26 UTC, ThomasK33 commented
Hey, @kirinnee, thanks for your PR.

Just so you know, I've reviewed it, and given that Kubernetes 1.23 has been EOL for seven months, it's safe to remove this version check here whatsoever. So, I've just removed it. ^^

2023-10-10 12:33 UTC, kirinnee commented
hi, good to know! thank you!

2023-10-10 12:59 UTC, merged