[DRAFT] Testing the GHA - PR for Adding tests for installing and deleting virtual cluster from kubectl
loft-sh/vcluster pull request #2013
Opened 2024-08-01 18:08 UTC by sowmyav27

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind test

- But this is for testing the GHA with some minor changes.
- Original PR: https://github.com/loft-sh/vcluster/pull/2011
- If this works, depending on how we want to proceed, I might close of these PRs

**What does this pull request do?**
Adds a test - install and delete vcluster using kubectl

**Please provide a short message that should be published in the vcluster release notes**
N/A

**What else do we need to know?**

2024-08-02 08:45 UTC, FabianKramm requested changes
Not sure if this is doing what we want, within our e2e test pipeline we want. The test itself looks good, but the problem is that the e2e pipeline itself is creating a vcluster as well via the regular method, it seems to me you only want to install & delete via kubectl and not want to have that other vcluster created as well. You either need to adjust the e2e pipeline itself for this (.github/workflows/e2e.yaml) or need to create a separate pipeline.

2024-08-02 12:29 UTC, zerbitx commented on test/e2e_vcluster_install/deploy_and_delete_vcluster.go
> +		}, pollingDurationLong, pollingInterval).Should(gomega.BeTrue(), "Virtual cluster failed to come up Active")
nit: Recommend using the "With" methods like [these](https://github.com/loft-sh/vcluster/blob/main/test/e2e_plugin/plugin/plugin.go#L30-L31)

2024-08-05 15:22 UTC, FabianKramm approved these changes

2024-08-05 15:24 UTC, FabianKramm requested changes
I tihnk whats weird is that we have all these different dimensions still for your new test. For what distros and dimensions do you want to run your test?

2024-08-06 09:24 UTC, FabianKramm approved these changes
@sowmyav27 LGTM! Thanks for the PR!

2024-08-06 09:25 UTC, merged