feat: add NetworkPolicy support
loft-sh/vcluster pull request #232
Opened 2021-12-06 16:04 UTC by matskiv

This should enable NetworPolicy synchronization with all necessary rewrites for the pod label selectors and namespace label selectors.

Fixes #155

2021-12-06 23:05 UTC, matskiv commented
I properly updated the code based on the recent changes in main + made this feature opt-in to allow easy installation even if the user doesn't have the permissions for network policies.
The new test will still fail, as there are at least two missing pieces here:
a) KinD cluster used for e2e tests probably needs to be configured with a different CNI plugin, one that supports network policies
b) New controller needs to be enabled in the deployments used for e2e tests. This might just be another devspace profile :thinking:

2021-12-10 06:04 UTC, olljanat commented
> a) KinD cluster used for e2e tests probably needs to be configured with a different CNI plugin, one that supports network policies

I see that you ended up disabling Calico now so recommend that you considering using K3s on network policy related e2e tests instead of KinD (and you can spin those with K3d) as it does support network policies without installing separate CNI.

2021-12-10 10:13 UTC, FabianKramm requested changes
@matskiv thanks for the PR! Please take a look at my comments, besides that it looks good!

2021-12-10 10:13 UTC, FabianKramm commented on charts/k0s/values.yaml
> +  extendedRolePermissions:
Please rename this to `rbac.role.extended`

2021-12-10 10:13 UTC, FabianKramm commented on charts/k3s/values.yaml
> +  extendedRolePermissions:
See above

2021-12-10 10:13 UTC, FabianKramm commented on charts/k8s/values.yaml
> +  extendedRolePermissions:
See above

2021-12-10 10:13 UTC, FabianKramm commented on devspace.yaml
> +          extendedRolePermissions:
see above

2021-12-10 10:13 UTC, FabianKramm commented on pkg/controllers/resources/networkpolicies/translate.go
> +func (s *syncer) translateUpdate(pObj, vObj *networkingv1.NetworkPolicy) (*networkingv1.NetworkPolicy, error) {
no error is ever returned here, so please omit it

2021-12-10 12:01 UTC, matskiv commented
@olljanat Thank you for the suggestion, I'll give it a shot :)

2021-12-14 16:52 UTC, matskiv commented
I addressed review comments.

As for the failing tests, after some investigation, it doesn't seem to be related to network policy changes. The failures happen due to a number of pod/exec calls which sometimes trigger yet unknown issue on the server that causes it to be temporarily unresponsive to new exec calls. I was not able to tell which component is causing this because multiple pods are marked as not ready when this happens, so it could be a problem on a lower network level... Anyway, since this is not caused by the network policy controller I will create a follow-up issue, and the tests will be skipped in CI for now.

2021-12-14 17:27 UTC, matskiv commented
@olljanat yes, that's the plan. Once this is merged a new beta release will be done.

2021-12-14 17:30 UTC, FabianKramm approved these changes
@matskiv LGTM! Thanks!

2021-12-14 17:30 UTC, merged