cli: notify user about incompatible workdir file
loft-sh/vcluster pull request #285
Opened 2022-01-10 15:51 UTC by matskiv

### Notable changes:

- cli: notify the user about incompatible workdir file when running `vcluster create`

2022-01-10 19:15 UTC, FabianKramm requested changes
@matskiv thanks for the PR! Please see my comments would be better to return an error instead of exiting immediately.

2022-01-10 19:15 UTC, FabianKramm commented on cmd/vclusterctl/cmd/create.go
> +		log.GetInstance().Fatal(fmt.Errorf("unable to get current work directory: %v", err))
Please return an error here instead of killing the program directly

2022-01-10 19:15 UTC, FabianKramm commented on cmd/vclusterctl/cmd/create.go
> +		log.GetInstance().Fatalf("Aborting vcluster creation. Current working directory contains a file or a directory with the name equal to the vcluster chart name - \"%s\". Please execute vcluster creat
See above

2022-01-11 11:02 UTC, matskiv commented
Yeah, good point. I updated the code to return the errors.

2022-01-11 12:17 UTC, FabianKramm approved these changes
@matskiv thanks! LGTM!

2022-01-11 12:17 UTC, merged