enhancement: add PR, bug report and feature request template
loft-sh/vcluster pull request #335
Opened 2022-01-26 07:25 UTC by pratikjagrut

Add github templates

2022-01-26 09:39 UTC, FabianKramm commented
@LukasGentele should we include these?

2022-01-26 11:34 UTC, matskiv commented
In the bug report, I would add a field for "Kubernetes distribution and version of the host cluster".

Do we need a Question type of issue too? Those are somewhat frequent. 
And if we do add a question template, I would maybe mention there that we have a Slack instance where they might get an answer quicker.

2022-01-27 16:04 UTC, LukasGentele requested changes
@FabianKramm I think this is a great idea. We should see how this goes and potentially add them to loft-sh/devspace repo as well. @pratikjagrut good job!

2022-01-31 06:50 UTC, pratikjagrut commented on .github/ISSUE_TEMPLATE/feature-request.md
> +    validations:
Good catch. Thank you.

2022-01-31 06:51 UTC, pratikjagrut commented on .github/ISSUE_TEMPLATE/feature-request.md
> +      label: **Is your feature request related to a problem?**
Oh yes, my bad.

2022-01-31 07:55 UTC, pratikjagrut commented
> In the bug report, I would add a field for "Kubernetes distribution and version of the host cluster".
> 
> Do we need a Question type of issue too? Those are somewhat frequent. And if we do add a question template, I would maybe mention there that we have a Slack instance where they might get an answer quicker.

@matskiv Thank you for the suggestions. I added a slack community link and the question you mentioned.

2022-01-31 08:08 UTC, pratikjagrut commented
> @FabianKramm I think this is a great idea. We should see how this goes and potentially add them to loft-sh/devspace repo as well. @pratikjagrut good job!
> 

@LukasGentele Thank you :) We have a basic template in the devspace repo. Here I tried to replicate the templates from the Kubernetes repo. So if these templates are accepted here then we can modify templates from the devspace repo too.

2022-01-31 08:13 UTC, FabianKramm approved these changes
@pratikjagrut thanks for the PR! LGTM!

2022-02-09 00:35 UTC, pratikjagrut commented
@LukasGentele Does this PR looks good to you?

2022-02-09 08:11 UTC, LukasGentele approved these changes
Looks great. Love it. Thanks!

2022-02-09 08:12 UTC, merged