Add init helm charts
loft-sh/vcluster pull request #515
Opened 2022-06-01 16:50 UTC by ishankhare07

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
Adds support to initialize a newly created vcluster with helm charts

**Please provide a short message that should be published in the vcluster release notes**
Add capability where vcluster and be initialized with helm charts.

**What else do we need to know?**

2022-06-13 09:41 UTC, FabianKramm requested changes
@ishankhare07 thanks for the PR! Please see my comments below. Would be also good if you add an e2e test that verifies this is correctly working.

2022-06-13 09:41 UTC, FabianKramm commented on pkg/controllers/manifests/init.go
> +	err = json.Unmarshal([]byte(lastConfigRaw), &lastConfig)
I guess its better to use bundle hash here only as the bundle is already compressed and would make up quite a big portion of the annotation here

2022-06-13 09:41 UTC, FabianKramm commented on pkg/controllers/manifests/init.go
> +	path, err := tarutil.ExtractTarGz(chartName, bytes.NewReader(tarball))
why extracting, you can also use `helm install test my-tar.tgz`

2022-06-21 06:57 UTC, ishankhare07 commented on Dockerfile
> +RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
I did test that and seems to work fine with all the e2e tests passing.

2022-06-21 08:05 UTC, FabianKramm requested changes
@ishankhare07 a couple of smaller things, please take a look at my comments below

2022-06-21 08:05 UTC, FabianKramm commented on pkg/controllers/manifests/init.go
> +	err = r.LocalClient.Update(ctx, cm, &client.UpdateOptions{})
You don't have to pass the updateoptions here

2022-06-21 08:05 UTC, FabianKramm commented on pkg/controllers/manifests/init.go
> +	err = r.LocalClient.Update(ctx, cm, &client.UpdateOptions{})
Remove update options here

2022-06-21 10:16 UTC, ishankhare07 commented on devspace.yaml
> +        init:
moving this to the `deploy` profile patches

2022-07-01 08:04 UTC, FabianKramm approved these changes
@ishankhare07 thanks for the PR! LGTM!

2022-07-01 08:04 UTC, merged