test: add e2e test for rootless mode
loft-sh/vcluster pull request #564
Opened 2022-06-28 07:36 UTC by pratikjagrut

**What issue type does this pull request address?** (keep at least one, remove the others)
/kind test

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #503

2022-06-29 04:45 UTC, olljanat reviewed
Thanks for this PR. We have been running K8s as rootless longtime already without issues. Only exception is that etcd needs fsGroup value which our policy controller adds automatically. Created PR #566 to fix it correctly in Helm charts now. 

It is also possible to harden those pods even more which why we most probably should test least privileged model at least with some variant. 

Here is maximum hardening which I have managed to get working. With those securityContexts vcluster will be able to run even on host cluster where https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted is enforced:
```yaml
syncer:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

etcd:
  fsGroup: 12345
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

controller:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

api:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault
```
But when tested it I found that seccompProfile is actually missing from pre-install job and CoreDNS which user cannot configure so created #567 to fix that issue.

However if these are too much for you PR I can created another one later to modify those rootless tests.

2022-06-29 04:45 UTC, olljanat commented on test/e2e_rootless/values.yaml
> +
assuming that #566 will get merged you should also add:
```yaml
fsGroup: 12345
```

2022-06-29 04:45 UTC, olljanat commented on test/e2e_rootless/values.yaml
> +    runAsNonRoot: true
assuming that #566 will get merged you should also add:
```yaml
etcd:
  fsGroup: 12345
```

2022-07-06 08:45 UTC, pratikjagrut commented
> However if these are too much for you PR I can created another one later to modify those rootless tests.

@olljanat Maybe we could have separate e2e for this because your config also has hardened security and isolation mode.

2022-07-06 15:21 UTC, matskiv requested changes
A change in .github/workflows/e2e.yaml is needed IMHO
The other comment is FYI only - change optional :)

2022-07-06 15:21 UTC, matskiv commented on .github/workflows/e2e.yaml
> +        kubectl logs -l app=${{ env.VCLUSTER_SUFFIX }} -n ${{ env.VCLUSTER_NAMESPACE }} -c vcluster --tail 500
Same as above

2022-07-06 15:21 UTC, matskiv commented on test/e2e_rootless/rootlessmode.go
> +		err = exec.Stream(remotecommand.StreamOptions{Stdout: &stdout})
btw, we have util to make exec easier - https://github.com/loft-sh/vcluster/blob/main/pkg/util/podhelper/exec.go#L152-L153

2022-07-07 08:04 UTC, matskiv approved these changes
LGTM. Thanks! :+1:

2022-07-07 14:38 UTC, FabianKramm approved these changes
@pratikjagrut thanks for the PR! LGTM!

2022-07-07 14:38 UTC, merged