added support for actions and conditions for alb ingress controller
loft-sh/vcluster pull request #570
Opened 2022-06-29 15:49 UTC by tukobadnyanoba

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #532 

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster ...serviceNames are translated to vcluster way of services

**What else do we need to know?**

2022-06-30 07:37 UTC, FabianKramm requested changes
@tukobadnyanoba thanks for the PR! Couple of comments below

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +func getActionOrConditionValue(annotation, actionOrCondition string) string {
Please only rewrite those annotations for the ingress syncer.

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +			fmt.Println(err)
Use klog instead of fmt.Println please

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +				&payload.ForwardConfig != nil &&
This check is not necessary

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +				&payload.ForwardConfig.TargetGroups != nil &&
This check is not necessary

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +					serviceName := targetGroup["serviceName"].(string)
Please make a safe cast here as this will panic otherwise if serviceName is not defined or if it is not a string

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +					if len(serviceName) > 0 {
Use serviceName != ""

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +					fmt.Println(err)
Use klog / loghelper here instead of fmt.Println

2022-06-30 07:37 UTC, FabianKramm commented on pkg/controllers/syncer/translator/namespaced_translator.go
> +	} else {
No else needed here

2022-06-30 08:53 UTC, matskiv submitted a review, later dismissed
Since this logic is specific for Ingress resource, I think it should be moved to one of the source files in `/pkg/controllers/resources/ingresses` 

Adding unit tests would be nice.

2022-07-05 20:49 UTC, FabianKramm approved these changes

2022-07-05 20:50 UTC, merged