add init charts documentation
loft-sh/vcluster pull request #581
Opened 2022-07-03 07:51 UTC by ishankhare07

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature
/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
Add documentation for init helm charts feature.

**Please provide a short message that should be published in the vcluster release notes**
Add docs for init helm charts

**What else do we need to know?**

2022-07-03 19:24 UTC, jschalz requested changes
Overall, great additions!

Besides some capitalizations, the biggest requests are
1. Making the "1. Upstream Mode" and "2. Bundle Mode" items relative links to where they are in the page. This lets a user click and be brought directly to that section, if they'd like.
2. Changing the #### headers to ###. Docusaurus needs descending header size to autogenerate sidebar items.

Something to consider: since the Bundle Mode has a significant number of command line steps, is there a way a user can verify that they've correctly followed everything? I'd love to see a "verify" section so a user can run it and gain some confidence.

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
>  Starting in version 0.8.0, vcluster allows users to apply manifests as soon as the vcluster is started. This can be useful for users configuring internal vcluster resources.
If this is accurate, I'd modify this from

> Starting in version 0.8.0, vcluster allows users to apply manifests as soon as the vcluster is started.

to

> Starting in version 0.8.0, vcluster allows users to apply manifests as soon as a virtual cluster is started.

It's a bit easier to distinguish the tool from the resource this way.

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +#### Upstream Mode
Please modify this to 3 #s instead of 4, for the docusaurus autogenerating.
#### Upstream Mode
to
### Upstream Mode

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +This is the most straight forward approach of applying a helm chart existing in and public/private upstream chart repository. the following examples demonstrate the usage:
`the following examples demonstrate the usage:`
Please capitalize the first word here.

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +If you're interested in applying a local chart directory, or a chart pulled from a repo that exists locally as a `tar` archive, then bundle mode can come handy. Let's say we have a chart named `my-ch
Please change the 
> #### Chart Bundle Mode
to
> ### Chart Bundle Mode
for the same reasons as "Upstream Mode".

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +# copy the chart to you clipboard
"you" > "your"

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +1. Upstream Mode
"1. Upstream Mode" to
1. [Upstream Mode](#upstream-mode)

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +2. Bundle Mode
"2. Bundle Mode" to
2. [Bundle Mode](#chart-bundle-mode)

2022-07-03 19:24 UTC, jschalz commented on docs/pages/operator/init-manifests.mdx
> +#### Chart Bundle mode
"mode" > "Mode"

2022-07-04 18:46 UTC, ishankhare07 commented
Hi @jschalz , thanks for the review. I've made the changes you requested. Regarding the suggestions about bundle mode unfortunately we don't have an way of verifying the bundled chart as of now. There are plans where we might think about integrating this whole flow into vcluster cli itself as a sub-command and make this whole thing automated.

2022-07-05 17:01 UTC, jschalz approved these changes
Awesome!! All looks good to me!!

With verification sections, we can always add it in the future as we have it!

2022-07-05 17:16 UTC, merged