Add background proxy container
loft-sh/vcluster pull request #662
Opened 2022-08-12 11:01 UTC by tukobadnyanoba

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves # https://github.com/loft-sh/vcluster-dd-extension/issues/22

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster ...now starts background-proxy container with `vcluster connect` command if the flag `--background-proxy` is specified. This doesn't need users to require the terminal open after user specifies `vcluster connect --background-proxy` 

**What else do we need to know?**

2022-08-15 15:30 UTC, FabianKramm requested changes

2022-08-15 15:30 UTC, FabianKramm commented on cmd/vclusterctl/cmd/connect.go
> +	if cmd.BackgroundProxy && localkubernetes.IsDockerInstalledAndUpAndRunning() {
Add a check here for `cmd.Server` being empty as otherwise starting a proxy container is unnecessary

2022-08-15 19:14 UTC, FabianKramm approved these changes

2022-08-15 19:14 UTC, merged

2022-09-30 15:19 UTC, tszyszko commented
Since this was merged in, you can no longer have multiple clusters in the same parent namespace. Is this intentional ? Our use-case involves multiple clusters created by CI, so multiple test clusters could be created on the fly in a single "test" namespace that has all the necessary restrictions applied in the host namespace.