feat: add HA configuration for vcluster
loft-sh/vcluster pull request #671
Opened 2022-08-18 11:45 UTC by pratikjagrut

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do?**
This pull request adds HA configuration for vcluster.

- The first pod-anti-affinity rule says that the scheduler should try to avoid scheduling the Pod onto a node with one or more Pods with the label app=vcluster.

- The second pod-anti-affinity rule says that the scheduler should try to avoid scheduling the Pod onto a node in the same zone as one or more Pods with the label app=vcluster.

- The pod Disruption Budget makes sure that there is a maximum 1 pod unavailable at a time.

**Please provide a short message that should be published in the vcluster release notes**
Added an HA configuration for vcluster.

2022-08-18 12:00 UTC, matskiv requested changes

2022-08-18 12:02 UTC, pratikjagrut commented on charts/k8s/values.yaml
> +    enableScheduler: true
oh yes
testing part

2022-08-18 12:06 UTC, pratikjagrut commented on charts/k8s/templates/api-deployment.yaml
> +      {{- if .Values.enableHA }}
Fabian said to enable it only if enableHA is enabled.

2022-08-18 12:06 UTC, pratikjagrut commented on charts/k8s/values.yaml
> +enableHA: true
test change, reverting it back.

2022-08-18 17:31 UTC, matskiv commented on charts/k8s/templates/api-deployment.yaml
> +      {{- if .Values.enableHA }}
Okay, but I would still reverse the condition order and first check if user set `.Values.api.affinity` to prefer that over our definition (with enableHA check).

2022-08-19 11:16 UTC, matskiv approved these changes
LGTM :) :

2022-08-22 07:29 UTC, FabianKramm approved these changes
@pratikjagrut thanks for the PR! LGTM!

2022-08-22 07:29 UTC, merged