search in right context for parent context vclusters
loft-sh/vcluster pull request #787
Opened 2022-10-14 11:55 UTC by bagulm123

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #786 

**Please provide a short message that should be published in the vcluster release notes**
Search in right context for parent context vclusters

**What else do we need to know?**

2022-10-14 15:38 UTC, matskiv commented on cmd/vclusterctl/cmd/find/find.go
> +		// check in all contexts - assuming parent context will be one of in all contexts.
This is a good point, the parent context might be present in a kubeconfig that was referenced by the env var too, and we won't have access to it.

2022-10-14 16:03 UTC, mtougeron commented
It's also worth noticing what I discovered this morning in https://github.com/loft-sh/vcluster/issues/786#issuecomment-1279011728

2022-10-14 16:06 UTC, matskiv commented
Actually, my previous comment would solve a potential issue, but not the one reported by @mtougeron in #786 
Currently `vcluster list` will show vclusters from the parent cluster if it detects that the current context is vcluster context, but in #786 it is requested to list only vclusters from the current context without trying to read the parent context.

2022-10-17 08:09 UTC, rohantmp commented
@matskiv @mahendrabagul 

I don't think it's a safe assumption that the config will have access to the parent cluster, and we should respect `--kubeconfig` and `KUBECONFIG` and I think we shouldn't try to access other kubeconfigs.

 IMO: Since we support nesting, `vcluster list` should not return sibling clusters, but we could warn that we are listing while connected to a vcluster.

2022-10-17 09:36 UTC, rohantmp requested changes
As per previous comment, I think we should review behavior around listing sibling clusters by looking up parent config.
We could do a quick fix that preserves the current behaviour by failing gracefully if parent context is not available.

2022-10-17 09:40 UTC, matskiv commented
> I don't think it's a safe assumption that the config will have access to the parent cluster, and we should respect --kubeconfig and KUBECONFIG and I think we shouldn't try to access other kubeconfig files. 

@rohantmp yes, I agree. On Fri I was so focused on how to make it work with other kubeconfig files, that I didn't think whether it is a good idea. :slightly_smiling_face: 

> IMO: Since we support nesting, vcluster list should not return sibling clusters, but we could warn that we are listing while connected to a vcluster.

Current `vcluster list` and `vcluster connect` behavior returns/connects to sibling clusters. I would keep it as is, especially considering that nested clusters are arguably a less popular use case. But I think we can support both use cases. I describe it in the last paragraph [of this comment](https://github.com/loft-sh/vcluster/issues/786#issuecomment-1279210679).

2022-10-19 10:00 UTC, rohantmp approved these changes
LGMT :)

2022-10-20 12:38 UTC, merged