Add Flag to clear node images from node status
loft-sh/vcluster pull request #826
Opened 2022-11-16 14:33 UTC by brandonrjacobs

**What issue type does this pull request address?** 
/kind enhancement

**What does this pull request do? Which issues does it resolve?**
This PR adds the capability to clear node images from the physical nodes when syncing down to the virtual node. 

**Please provide a short message that should be published in the vcluster release notes**
Enabling `node-clear-image-status` clears all `status.images` from the node when it is synced to the virtual cluster. Images can leak information about a node when running in a multi-tenant environment where customers share the nodes they run on. Enabling this flag helps prevent information leaking.

2022-11-16 17:44 UTC, brandonrjacobs commented on cmd/vcluster/context/flag_options.go
> +	SyncAllNodes        bool     `json:"syncAllNodes,omitempty"`
I just realized this format change happened, happy to revert this back if you prefer.

2022-11-18 10:53 UTC, FabianKramm requested changes
@brandonrjacobs thanks a lot for the PR! Looks good so far, but you are missing the actual flag registration at https://github.com/loft-sh/vcluster/blob/a73194ef886d506326eead261e6e185cdef52d84/cmd/vcluster/context/flag_options.go#L92 .

2022-11-18 13:05 UTC, brandonrjacobs commented
@FabianKramm thanks! Rebase issue there, I'll add it back!

2022-11-21 22:26 UTC, brandonrjacobs commented
@FabianKramm just tagging here -- let me know how this looks and if you'd like me to undo that formatting change.

2022-12-05 16:09 UTC, FabianKramm approved these changes

2022-12-05 16:36 UTC, merged